apiVersion: v1
kind: ConfigMap
metadata:
  name: tikrai-mail-receiver-config
data:
  APP_SMTP_ACCEPTED_DOMAIN: "tikrai.com"
  APP_FORWARD_URL: "http://tikrai-server-service:8080/api/admin/aggregateemail"
  APP_SMTP_PORT: "2525"
  APP_FORWARD_TIMEOUT_MS: "5000"
