apiVersion: v1
kind: ConfigMap
metadata:
  name: tikrai-mail-receiver-config
  namespace: tikrai-mail
data:
  APP_SMTP_ACCEPTED_DOMAIN: "tikrai.com"
  APP_FORWARD_URL: "http://tikrai-server-service.default.svc.cluster.local:8080/api/admin/aggregateemail"
  APP_FORWARD_AUTH_HEADER_NAME: "X-Api-Key"
  APP_SMTP_PORT: "2525"
  APP_FORWARD_TIMEOUT_MS: "5000"
