# This secret should be created using kubectl command:
# kubectl create secret docker-registry registry-tikrai-secret \
#   --docker-server=registry.digitalocean.com \
#   --docker-username=<your-do-access-token> \
#   --docker-password=<your-do-access-token> \
#   --docker-email=<your-email> \
#   --namespace=tikrai-mail
#
# Or using DO access token directly:
# kubectl create secret docker-registry registry-tikrai-secret \
#   --docker-server=registry.digitalocean.com \
#   --docker-username=<your-do-access-token> \
#   --docker-password=<your-do-access-token> \
#   --namespace=tikrai-mail
#
# Note: For DigitalOcean Container Registry, username and password are both the DO access token
#
# This file is kept for reference only - do not apply it directly

