apiVersion: apps/v1
kind: Deployment
metadata:
  name: tikrai-mail-receiver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tikrai-mail-receiver
  template:
    metadata:
      labels:
        app: tikrai-mail-receiver
    spec:
      imagePullSecrets:
        - name: registry-tikrai-secret
      containers:
        - name: app
          image: ghcr.io/labordi/tikrai-mail-receiver:0.1.0
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
            - name: smtp
              containerPort: 2525
          env:
            - name: APP_FORWARD_URL
              valueFrom:
                configMapKeyRef:
                  name: tikrai-mail-receiver-config
                  key: APP_FORWARD_URL
            - name: APP_SMTP_ACCEPTED_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: tikrai-mail-receiver-config
                  key: APP_SMTP_ACCEPTED_DOMAIN
            - name: APP_SMTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: tikrai-mail-receiver-config
                  key: APP_SMTP_PORT
            - name: APP_FORWARD_TIMEOUT_MS
              valueFrom:
                configMapKeyRef:
                  name: tikrai-mail-receiver-config
                  key: APP_FORWARD_TIMEOUT_MS

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
