apiVersion: v1
kind: Service
metadata:
  name: tikrai-mail-receiver-smtp
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "tcp"
    service.beta.kubernetes.io/do-loadbalancer-algorithm: "round_robin"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-protocol: "tcp"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-port: "25"
spec:
  type: LoadBalancer
  selector:
    app: tikrai-mail-receiver
  ports:
    - name: smtp
      port: 25
      targetPort: 2525
      protocol: TCP
