apiVersion: v1
kind: Service
metadata:
  name: tikrai-mail-receiver-smtp
  namespace: tikrai-mail
spec:
  type: LoadBalancer
  selector:
    app: tikrai-mail-receiver
  ports:
    - name: smtp
      port: 2525
      targetPort: 2525
      protocol: TCP
